### ISSUE TITLE
New "Live events" tab. Opinions requested!

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#13]
I made a new feature where the app has a tab at the top to select between "WWDC" and "Live Events". On the "Live Events" tab It is possible to watch previous special events (not necessarily WWDC-related). I am also planning on making the live stream available the day of the keynote.

If you want to test this new functionality, checkout the [live-events](https://github.com/insidegui/WWDC/tree/live-events) branch.

I don't know if I should add this to the app, maybe It distracts from It's main purpose. *What do you think?*

![captura de tela 2015-04-25 as 17 32 37](https://cloud.githubusercontent.com/assets/67184/7334717/30eb5c26-eb71-11e4-8b0b-0d8911d7a4f8.png)

**Comment by zortje** [comment]
Maybe call it "Keynotes" or "Special Events"; "Live Events" could imply that it is just for actual LIVE events.

But considering that Apple has podcasts for the special events and that people watch them live (on Apple TV as an example), maybe it is better to leave it out and focus on WWDC related stuff.
Otherwise you might need to change the app name ;)

**Comment by art-divin** [comment]
+1 for Keynotes;
(live event) cell details text looks redundant, would be better to replace it with Keynote, or maybe removing it completely, since it is the same for all items

**Comment by insidegui** [comment]
Renamed to "keynotes". Still not sure if I'll really add this to the app.

But I'll definitely make something that will enable people to watch the WWDC keynote live through the app :)
