### ISSUE TITLE
AirPlay icon misplaced beneath playback speed

### ISSUE THREAD

**Issue by UberJason** [insidegui/WWDC#130]
See screenshot below: the AirPlay button is beneath the playback speed button, which means it's not possible to AirPlay this video because only the playback speed button registers the click.
![airplay](https://cloud.githubusercontent.com/assets/5779307/15526339/38488c3a-21ff-11e6-9af9-aeeb341fc7ee.png)

**Comment by insidegui** [comment]
I fixed this by simply removing that button, It never looked right to me since the player shows the current speed when It's changed. To cycle between playback rates there's a menu option now with shortcut:
![captura de tela 2016-06-06 as 12 20 37](https://cloud.githubusercontent.com/assets/67184/15827246/225985fa-2be1-11e6-82ff-a21cb9b21c8b.png)
