### ISSUE TITLE
Add schedule of upcoming WWDC events / sessions

### ISSUE THREAD

**Issue by EliyahuStern** [insidegui/WWDC#132]

**Comment by natecook1000** [comment]
@insidegui Don't know if it helps before it's live on the web service, but there's a branch here with the (mostly redacted) 2016 sessions: https://github.com/ASCIIwwdc/wwdc-session-transcripts/tree/wwdc2016

**Comment by insidegui** [comment]
Hi people! I'm working on It. Apple's API already provides the list of sessions so getting It is not a problem. The code part is relatively straightforward, I'm actually having more trouble deciding how to do it in terms of UX, but we'll have the schedule up before next monday 😅

**Comment by insidegui** [comment]
Here's what I've done:

The scheduled sessions are listed on the sidebar, ordered by date and time. They look different from the videos and when the session is live there is a "live" indicator (screenshot above).

**Only sessions with an associated video are shown**, therefore the labs are not. Since this app is mostly focused on the videos and live sessions I don't think this is a major issue.

![captura de tela 2016-06-06 as 23 46 01](https://cloud.githubusercontent.com/assets/67184/15844728/f8197ea0-2c42-11e6-830d-f1d6d336988a.png)

**Comment by EliyahuStern** [comment]
Thanks, looking great!

I was able to build this one from source, but `brew cask update wwdc` didn't work. When will it be available in brew?

**Comment by insidegui** [comment]
I think brew gets the release version. The release will be available later today ;)

**Comment by insidegui** [comment]
@EliyahuStern Be sure to update to the release version as soon as It's out because the debug version may not update correctly.
