### ISSUE TITLE
Search through ASCII WWDC transcripts in main screen

### ISSUE THREAD

**Issue by mac-cain13** [insidegui/WWDC#21]
Currently it's only possible to search through the transcript when watching the video. Often I remembers some keywords of a talk, but don't know which one it was about that specific topic. It would be great if the searchbar in the main window with the overview of all videos also searched in the transcripts.

I would imagine that search results are ordered like this:
- hit in the title 
- hit in description
- number of hits in transcript

**Comment by insidegui** [comment]
I don't know, I think this would make the search too complicated.

Currently the transcripts are only downloaded when the transcript window is opened, and the processing of the transcripts is quite expensive, It would be hard to search through all of them on every single keystroke.

That said, if anyone wants to tackle this, go ahead :)

**Comment by art-divin** [comment]
I am almost done with this one.. :wink:

**Comment by insidegui** [comment]
=3

**Comment by art-divin** [comment]
@insidegui I've implemented transcript search, and the keyword is `transcript`. Would be great to add it to README.md...

I had to set -[NSSearchFieldCell setSendsWholeSearchString:] to `YES` because otherwise there would be too much request being sent to `asciiwwdc.com` endpoint.

However, this implies that now users have to press "Enter" in order to start search

**Comment by insidegui** [comment]
As discussed in [this defunct pull request](https://github.com/insidegui/WWDC/pull/26), the best approach will be to cache the transcripts locally and search the local cache.

@art-divin do you want to make this or do you want me to make It? Maybe I can do the cache thing and you can do the search, what do you think?

**Comment by art-divin** [comment]
@insidegui I think it should be separated into 3 aspects:

1. "Fetch Transcripts" Service implementation (you can do that, I've no experience of working with XPC)
(on the second thought, this can be implemented via NSURLSession...). This might include class extension for existing WWDCSessionTranscript object model due to the fact that matches should be counted
2. CoreData - I can do that, basic trick is to "normalize" contents of the transcripts into lowercased indexed strings which will repeat existing class hierarchy
3. UI - this can include number of improvements, including:
 * Moving search method to async mode
 * Async updates of table
 * Sorting according to priorities (query match (year, rank, [...]), title match, description match, number of matches in transcript)

I can see implementation as 3-part one: 

1. Update existing model
2. Implement CoreData
3. Implement Networking
4. Implement UI

UI cannot be done unless everything else is done, so I would say that I'll be able to extend existing model and CoreData, but I need a bit of assistance in Networking.

As for UI, I can implement basic thing and you'll be able to improve the looks, if needed.

**Comment by art-divin** [comment]
@insidegui I've started with this feature, I'll do it myself :wink:

**Comment by art-divin** [comment]
@insidegui I am sorry for a very delayed response , had a lot of work to do.
I've actually implemented this like 3 weeks ago, but I was really not satisfied with memory usage performance.
What I would suggest to do is for now just have CoreData enabled just for caching Transcripts (since they don't change over time at all), and leave searching through them for future.
What do you think?

**Comment by insidegui** [comment]
I have an implementation using YapDatabase (It uses SQLite's FTS module for really fast text search), I just need to get the interface right, the performance is good.

**Comment by insidegui** [comment]
Ok, now I have the search working, using the qualifier "transcript". To search for a phrase you can put the query in quotes like `transcript:"window chrome"`.

The performance seems ok on my Mid 2011 iMac, I thought about putting a progress indicator during slow searches but I don't know if it's necessary or not.

**Comment by insidegui** [comment]
Ugh, actually the quotes don't work to search for phrases, It seems like the search will find anything that matches ANY word, I'll see what I can do about It...

**Comment by insidegui** [comment]
This is working quite well (for me at least). I think I'll close this issue for now.
