### ISSUE TITLE
App won't load anything

### ISSUE THREAD

**Issue by fuzunspm** [insidegui/WWDC#225]
It keeps loading without actually displaying anything on the app.

Version: 5.0.6

![screen shot 2017-06-06 at 12 11 24 pm](https://cloud.githubusercontent.com/assets/12132746/26822062/6c64bc92-4ab1-11e7-9e50-8917a2eaeea4.png)

**Comment by insidegui** [comment]
What's the OS version?
Have you tried using a different network?
Anything in the console?

**Comment by nRewik** [comment]
I have the same problem. It's the latest macOS Sierra.

**Comment by allanrojas** [comment]
Same issue here... :(

**Comment by insidegui** [comment]
Can you open Console.app and run the app, search for "WWDC", copy and paste the contents of the console here?

**Comment by allanrojas** [comment]
par défaut	11:14:53.316441 -0600	WWDC	Faulting in NSHTTPCookieStorage singleton
par défaut	11:14:53.316473 -0600	WWDC	Faulting in CFHTTPCookieStorage singleton
par défaut	11:14:53.316496 -0600	WWDC	Creating default cookie storage with process/bundle identifier
par défaut	11:14:53.320300 -0600	WWDC	UNIX error exception: 17
par défaut	11:14:53.320886 -0600	WWDC	0x608001664c40 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
par défaut	11:14:53.322507 -0600	WWDC	UNIX error exception: 17
par défaut	11:14:53.322907 -0600	WWDC	UNIX error exception: 17
par défaut	11:14:53.323099 -0600	WWDC	UNIX error exception: 17
par défaut	11:14:53.323547 -0600	WWDC	UNIX error exception: 17
par défaut	11:14:53.323734 -0600	WWDC	UNIX error exception: 17
par défaut	11:14:53.323863 -0600	WWDC	0x608001668880 opened /Users/gromrojas/Library/Keychains/login.keychain-db: 1570268 bytes
par défaut	11:14:53.329564 -0600	WWDC	0x608001668600 opened /Library/Keychains/System.keychain: 220740 bytes
par défaut	11:14:53.334290 -0600	WWDC	TIC TCP Conn Start [1:0x60800038a420]
erreur	11:14:53.358075 -0600	WWDC	Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.
par défaut	11:14:53.425973 -0600	WWDC	TIC TCP Conn Event [1:0x60800038a420]: 1 Err(0)
par défaut	11:14:53.426006 -0600	WWDC	TIC TCP Conn Connected [1:0x60800038a420]: Err(0)
par défaut	11:14:53.426111 -0600	WWDC	TIC Enabling TLS [1:0x60800038a420]
par défaut	11:14:53.507935 -0600	WWDC	TIC TLS Event [1:0x60800038a420]: 2, Pending(0)
par défaut	11:14:53.509672 -0600	WWDC	TIC TLS Event [1:0x60800038a420]: 11, Pending(0)
par défaut	11:14:53.510022 -0600	WWDC	UNIX error exception: 17
par défaut	11:14:53.510287 -0600	WWDC	UNIX error exception: 17
par défaut	11:14:53.510931 -0600	WWDC	TIC TLS Event [1:0x60800038a420]: 12, Pending(0)
par défaut	11:14:53.510976 -0600	WWDC	TIC TLS Event [1:0x60800038a420]: 14, Pending(0)
par défaut	11:14:53.524833 -0600	WWDC	TIC TCP Conn Start [2:0x6000001941c0]
par défaut	11:14:53.529450 -0600	WWDC	TIC TLS Trust Result [1:0x60800038a420]: 0
par défaut	11:14:53.570778 -0600	WWDC	Live event observer not started because we're not on WWDC week
par défaut	11:14:53.584424 -0600	WWDC	[Crashlytics] Version 3.8.4 (121)
par défaut	11:14:53.598721 -0600	WWDC	TIC TCP Conn Start [3:0x60800038bbb0]
par défaut	11:14:53.612684 -0600	WWDC	TIC TLS Event [1:0x60800038a420]: 20, Pending(0)
par défaut	11:14:53.614608 -0600	WWDC	TIC TCP Conn Event [1:0x60800038a420]: 8 Err(0)
par défaut	11:14:53.614635 -0600	WWDC	TIC TLS Handshake Complete [1:0x60800038a420]
par défaut	11:14:53.620666 -0600	WWDC	TIC TCP Conn Start [4:0x60800038ab70]
par défaut	11:14:53.663065 -0600	WWDC	TIC TCP Conn Event [2:0x6000001941c0]: 1 Err(0)
par défaut	11:14:53.663090 -0600	WWDC	TIC TCP Conn Connected [2:0x6000001941c0]: Err(0)
par défaut	11:14:53.663182 -0600	WWDC	TIC Enabling TLS [2:0x6000001941c0]
par défaut	11:14:53.711491 -0600	WWDC	TIC TCP Conn Event [3:0x60800038bbb0]: 1 Err(0)
par défaut	11:14:53.711521 -0600	WWDC	TIC TCP Conn Connected [3:0x60800038bbb0]: Err(0)
par défaut	11:14:53.711614 -0600	WWDC	TIC Enabling TLS [3:0x60800038bbb0]
par défaut	11:14:53.717980 -0600	WWDC	TIC TCP Conn Event [4:0x60800038ab70]: 1 Err(0)
par défaut	11:14:53.718008 -0600	WWDC	TIC TCP Conn Connected [4:0x60800038ab70]: Err(0)
par défaut	11:14:53.718124 -0600	WWDC	TIC Enabling TLS [4:0x60800038ab70]
par défaut	11:14:53.731206 -0600	WWDC	TIC TLS Event [2:0x6000001941c0]: 2, Pending(0)
par défaut	11:14:53.735712 -0600	WWDC	TIC TLS Event [2:0x6000001941c0]: 11, Pending(0)
par défaut	11:14:53.736134 -0600	WWDC	TIC TLS Event [2:0x6000001941c0]: 22, Pending(0)
par défaut	11:14:53.736592 -0600	WWDC	TIC TLS Event [2:0x6000001941c0]: 12, Pending(0)
par défaut	11:14:53.736633 -0600	WWDC	TIC TLS Event [2:0x6000001941c0]: 14, Pending(0)
par défaut	11:14:53.742090 -0600	WWDC	TIC TLS Trust Result [2:0x6000001941c0]: 0
par défaut	11:14:53.800034 -0600	WWDC	[LiveObserver] Error creating subscriptions: <CKError 0x60000044e2b0: "Not Authenticated" (9/1002); "CloudKit access was denied by user settings"; Retry after 3.0 seconds>
par défaut	11:14:53.801325 -0600	WWDC	[RemoteEnvironment] Error creating subscription: <CKError 0x6080006442f0: "Not Authenticated" (9/1002); "CloudKit access was denied by user settings"; Retry after 3.0 seconds>
par défaut	11:14:53.802410 -0600	WWDC	TIC TLS Event [4:0x60800038ab70]: 2, Pending(0)
par défaut	11:14:53.808119 -0600	WWDC	TIC TLS Event [4:0x60800038ab70]: 11, Pending(0)
par défaut	11:14:53.809167 -0600	WWDC	TIC TLS Event [2:0x6000001941c0]: 20, Pending(0)
par défaut	11:14:53.809529 -0600	WWDC	TIC TLS Event [4:0x60800038ab70]: 12, Pending(0)
par défaut	11:14:53.809896 -0600	WWDC	TIC TLS Event [4:0x60800038ab70]: 14, Pending(0)
par défaut	11:14:53.810008 -0600	WWDC	TIC TCP Conn Event [2:0x6000001941c0]: 8 Err(0)
par défaut	11:14:53.810050 -0600	WWDC	TIC TLS Handshake Complete [2:0x6000001941c0]
par défaut	11:14:53.813118 -0600	WWDC	TIC TLS Event [3:0x60800038bbb0]: 2, Pending(0)
par défaut	11:14:53.817833 -0600	WWDC	TIC TLS Event [3:0x60800038bbb0]: 11, Pending(0)
par défaut	11:14:53.818315 -0600	WWDC	TIC TLS Event [3:0x60800038bbb0]: 12, Pending(0)
par défaut	11:14:53.818364 -0600	WWDC	TIC TLS Event [3:0x60800038bbb0]: 14, Pending(0)
par défaut	11:14:53.820524 -0600	WWDC	TIC TLS Trust Result [3:0x60800038bbb0]: 0
par défaut	11:14:53.838392 -0600	WWDC	TIC TLS Trust Result [4:0x60800038ab70]: 0
par défaut	11:14:53.920052 -0600	WWDC	TIC TLS Event [3:0x60800038bbb0]: 20, Pending(0)
par défaut	11:14:53.920088 -0600	WWDC	TIC TLS Event [4:0x60800038ab70]: 20, Pending(0)
par défaut	11:14:53.920601 -0600	WWDC	TIC TCP Conn Event [4:0x60800038ab70]: 8 Err(0)
par défaut	11:14:53.920601 -0600	WWDC	TIC TCP Conn Event [3:0x60800038bbb0]: 8 Err(0)
par défaut	11:14:53.920651 -0600	WWDC	TIC TLS Handshake Complete [3:0x60800038bbb0]
par défaut	11:14:53.920656 -0600	WWDC	TIC TLS Handshake Complete [4:0x60800038ab70]
par défaut	11:14:53.923401 -0600	WWDC	TIC TCP Conn Start [5:0x608000390e90]
par défaut	11:14:54.028533 -0600	WWDC	TIC TCP Conn Event [5:0x608000390e90]: 1 Err(0)
par défaut	11:14:54.028675 -0600	WWDC	TIC TCP Conn Connected [5:0x608000390e90]: Err(0)
par défaut	11:14:54.031207 -0600	WWDC	TIC Enabling TLS [5:0x608000390e90]
par défaut	11:14:54.063963 -0600	WWDC	TIC TCP Conn Cancel [3:0x60800038bbb0]
par défaut	11:14:54.093574 -0600	WWDC	TIC TCP Conn Start [6:0x600000197b70]
par défaut	11:14:54.112735 -0600	WWDC	TIC TLS Event [5:0x608000390e90]: 2, Pending(0)
par défaut	11:14:54.112828 -0600	WWDC	TIC TLS Event [5:0x608000390e90]: 20, Pending(0)
par défaut	11:14:54.113336 -0600	WWDC	TIC TCP Conn Event [5:0x608000390e90]: 8 Err(0)
par défaut	11:14:54.113358 -0600	WWDC	TIC TLS Handshake Complete [5:0x608000390e90]
par défaut	11:14:54.169838 -0600	WWDC	TIC TCP Conn Event [6:0x600000197b70]: 1 Err(0)
par défaut	11:14:54.169872 -0600	WWDC	TIC TCP Conn Connected [6:0x600000197b70]: Err(0)
par défaut	11:14:54.169977 -0600	WWDC	TIC Enabling TLS [6:0x600000197b70]
par défaut	11:14:54.234760 -0600	WWDC	TIC TLS Event [6:0x600000197b70]: 2, Pending(0)
par défaut	11:14:54.237292 -0600	WWDC	TIC TLS Event [6:0x600000197b70]: 11, Pending(0)
par défaut	11:14:54.238661 -0600	WWDC	TIC TLS Event [6:0x600000197b70]: 22, Pending(0)
par défaut	11:14:54.238819 -0600	WWDC	TIC TLS Event [6:0x600000197b70]: 12, Pending(0)
par défaut	11:14:54.238884 -0600	WWDC	TIC TLS Event [6:0x600000197b70]: 14, Pending(0)
par défaut	11:14:54.250980 -0600	WWDC	TIC TLS Trust Result [6:0x600000197b70]: 0
par défaut	11:14:54.317159 -0600	WWDC	TIC TLS Event [6:0x600000197b70]: 20, Pending(0)
par défaut	11:14:54.317556 -0600	WWDC	TIC TCP Conn Event [6:0x600000197b70]: 8 Err(0)
par défaut	11:14:54.317596 -0600	WWDC	TIC TLS Handshake Complete [6:0x600000197b70]
par défaut	11:14:54.319684 -0600	WWDC	TIC TCP Conn Start [7:0x600000197760]
par défaut	11:14:54.397582 -0600	WWDC	TIC TCP Conn Event [7:0x600000197760]: 1 Err(0)
par défaut	11:14:54.397618 -0600	WWDC	TIC TCP Conn Connected [7:0x600000197760]: Err(0)
par défaut	11:14:54.397806 -0600	WWDC	TIC Enabling TLS [7:0x600000197760]
par défaut	11:14:54.482810 -0600	WWDC	TIC TLS Event [7:0x600000197760]: 2, Pending(0)
par défaut	11:14:54.484767 -0600	WWDC	TIC TLS Event [7:0x600000197760]: 11, Pending(0)
par défaut	11:14:54.489114 -0600	WWDC	TIC TLS Event [7:0x600000197760]: 22, Pending(0)
par défaut	11:14:54.489575 -0600	WWDC	TIC TLS Event [7:0x600000197760]: 12, Pending(0)
par défaut	11:14:54.489666 -0600	WWDC	TIC TLS Event [7:0x600000197760]: 14, Pending(0)
par défaut	11:14:54.502257 -0600	WWDC	TIC TLS Trust Result [7:0x600000197760]: 0
par défaut	11:14:54.582898 -0600	WWDC	TIC TLS Event [7:0x600000197760]: 20, Pending(0)
par défaut	11:14:54.583819 -0600	WWDC	TIC TCP Conn Event [7:0x600000197760]: 8 Err(0)
par défaut	11:14:54.583875 -0600	WWDC	TIC TLS Handshake Complete [7:0x600000197760]
par défaut	11:14:55.909216 -0600	WWDC	Live event observer not started because we're not on WWDC week
par défaut	11:15:03.818062 -0600	WWDC	TIC TCP Conn Event [1:0x60800038a420]: 2 Err(0)
par défaut	11:15:03.818136 -0600	WWDC	TIC TCP Conn Cancel [1:0x60800038a420]
par défaut	11:15:03.818253 -0600	WWDC	TIC TCP Conn Destroyed [1:0x60800038a420]
par défaut	11:15:24.319276 -0600	WWDC	TIC TCP Conn Cancel [5:0x608000390e90]

**Comment by allanrojas** [comment]
I'm curious it says CloudKit denied, but I am logged in to my iCloud account on the mac.

**Comment by insidegui** [comment]
@allanrojas Can you send me a screenshot of your time settings in System Preferences > Date & Time > Clock and a screenshot of the language settings in System Preferences > Language & Region ?

I believe this issue is related to timezone/region (I've had a similar issue on another app).

**Comment by allanrojas** [comment]
http://imgur.com/a/Vo3rg

http://imgur.com/yBXOF1S

**Comment by insidegui** [comment]
I tested the app in a virtual machine using the same settings and in fact it doesn't load. I'll get this fixed for the next release. Thanks for your help!
