### ISSUE TITLE
Cannot download most WWDC17 videos

### ISSUE THREAD

**Issue by melgu** [insidegui/WWDC#231]
Currently I can only download the Platforms State of the Union, but everything else is stream only.

**Comment by bdash** [comment]
From what I can tell, Apple hasn't posted downloadable videos for anything but the Platforms State of the Union and Whats New in Swift at this point. You can double-check this by clicking around the videos posted on https://developer.apple.com/videos/wwdc2017/ and noting that no other sessions have downloads listed in their Resources tab.

**Comment by bitomule** [comment]
I already see the downloads on iOS Apple apps but not on OS X app. Maybe Apple changed something for this videos?

(BTW, great work, awesome app)

**Comment by bdash** [comment]
A number of downloadable session videos have been posted since my previous comment (Introducing Password Autofill for Apps, What's New in Cocoa, and others). These are all appearing as downloadable for me in the WWDC app on Mac. It's worth noting that the official WWDC app on iOS appears to have a rendering bug that causes many videos to incorrectly appear as downloadable in the table view. Tapping on the download button for those videos has no effect, and navigating down to the video's detail screen reveals that they're not in fact downloadable.

(Note also that I'm just an interested user, and am not involved with the development of the WWDC app in any way.)

**Comment by bitomule** [comment]
What's New in Cocoa still not available in OS X app for me.

**Comment by ornithocoder** [comment]
For now, one can workaround the fact that Apple didn't post the link to the videos by building the URL to download the video.

Take https://developer.apple.com/videos/play/wwdc2017/816/ as example. Simply copy the slides link

https://devstreaming-cdn.apple.com/videos/wwdc/2017/816mg1phgy05k3v/816/816_love_at_first_launch.pdf

add `_hd_` after the session number and replace `.pdf` by `.mp4?dl=1`

https://devstreaming-cdn.apple.com/videos/wwdc/2017/816mg1phgy05k3v/816/816_hd_love_at_first_launch.mp4?dl=1

Voilà.

**Comment by insidegui** [comment]
Downloads become available when the downloadable asset is added to Apple's HTTP API. Currently only the Platforms State of the Union has a downloadable asset posted.

Until they update the feed, there's nothing I can do.
