### ISSUE TITLE
Playback speed resets to 1x upon an interactive seek

### ISSUE THREAD

**Issue by balazsgerlei** [insidegui/WWDC#265]
- Version of macOS
10.12.5
- Version of the app
5.1.2
- What were you trying to do when the issue happened
- If it is a wrong behavior, list all steps required to reproduce it
Watch a video in faster speed (ex. 1/2x, 1.25x or 1.5x), and then skip back to a previous timestamp with the seeker. If I click to any part of the seeker, the video jumps to the correct timestamp, but the playback speed resets to 1x. The control to change speed still indicates the speed I choose, but the video continues to play back in 1x until I change the playback speed again.

**Comment by bcmn** [comment]
I've diagnosed this issue further, and I'm confident it only occurs on an "interactive" seek -- in which the timeline is clicked and then dragged to scrub through. On rare occasions normal seek-to-point actions can be interpreted as "interactive", which is why it can appear as though this issue occurs on during other interactions. I've updated the info to match, and I'll work on fixing this as soon as I can.
