### ISSUE TITLE
All subtitling options aren't always embedded in downloaded videos

### ISSUE THREAD

**Issue by bcmn** [insidegui/WWDC#267]
Version: 5.1.2

Symptoms:
- The subtitles button fails to show on many downloaded 2017 videos, as when downloaded, no closed captions are embedded. (This can be tested by checking for embedded subtitles in other applications)
- When clicking the subtitle button on a downloaded video from previous years, only English subtitles are present.

**Comment by Huang-Libo** [comment]
Same problem.

**Comment by bcmn** [comment]
I've updated the title & description of this issue with more observations on behaviour. 

Intriguingly, the iOS app _does_ offer closed captions on 2017 downloaded videos. We're not clear if they're downloading the streaming video directly, instead of relying on the separate SD/HD download, or whether there might be some other solution to this.

**Comment by insidegui** [comment]
@bcmn Thanks for saving this issue 🤓

**Comment by Huang-Libo** [comment]
Problem still remain in version 6.2

**Comment by insidegui** [comment]
It's been a while 😅

So I've spent some time implementing an entirely new downloading system that can take advantage of `AVAssetDownloadURLSession` in order to download the HLS stream, which includes all subtitle options in the downloaded content. 

I'll try to get this integrated into the app before the videos come out for this years WWDC 🤓
