### ISSUE TITLE
How one can run the tests?

### ISSUE THREAD

**Issue by otaviolima** [insidegui/WWDC#296]
I was trying to run the tests but encountered a lot of compiler errors and after fixing some and commenting out others I still was not able to run.

From the error is pretty obvious that is due some code signing process.

My questions then are:

Would be a person not enrolled as mac developer in Apple Developer Center able to run the tests?

If so, is the current code correct and compiling? At least for me, as I mentioned earlier, it did not compile.

**Comment by insidegui** [comment]
Unfortunately, the tests are currently very outdated and are not compiling. I developed ConfCore (data parsing and storage) a long time ago with tests and when the time came to actually put the app into production I didn't have enough time to do proper TDD or update the tests. To make that even worse, a few days before WWDC Apple changed the data structure completely and that completely invalidated the tests (and made I leave some messy code in there because of the time pressure).

**Comment by SpacyRicochet** [comment]
Sounds like a nice [Hacktoberfest[(https://hacktoberfest.digitalocean.com) issue. Consider adding that label to some of the issues here.

**Comment by Ethenyl** [comment]
Hi there,

I'm more than willing to help on that topic, if it's OK on your side I'll create a PR as soon as I have something stable.

**Comment by insidegui** [comment]
@Ethenyl That would be great, go ahead 🚀
