### ISSUE TITLE
Feature Request: Display a List of Related Videos

### ISSUE THREAD

**Issue by nik6018** [insidegui/WWDC#331]
Hi gui,

Thanks for the amazing Mac App the official iOS version is horrible, I have been using the App for a week and think the following may make the UX better.

It would be great if the app can have a related video's section under the Main Video view.

The WWDC app for iOS does this and this is very helpful for finding related videos on a topic that you watch.

Otherwise, I have to search for the Video first on the iOS app check the related videos and then search for the exact name of the session in the Mac App.

Don't know if this can be implemented if you are just scrapping Apple's website for videos, hoping for the best.

Would love to help to get this feature implemented if it's possible.

**Comment by insidegui** [comment]
This data is actually available from the API, so it can definitely be done 😄

**Comment by nik6018** [comment]
Thanks gui.
Hope an amateur like me can help in some way.

**Comment by bcmn** [comment]
Worth noting here that I've begun working on the JSON parsing for this, & we've requested an update from the UI designer to take it into account. I was on a train so I couldn't push the changes, but will ASAP.

**Comment by insidegui** [comment]
Thanks @bcmn !

**Comment by VicenteBorrell** [comment]
Hi guys! It's been a while! 😄 

I just made this two proposals for this feature. Let me know what you think.

![related videos section](https://user-images.githubusercontent.com/584834/37118023-239a6776-2253-11e8-84c7-fe6112b0a230.png)
![overview with related](https://user-images.githubusercontent.com/584834/37118025-23c313e2-2253-11e8-8b89-3676a8ae4d27.png)

**Comment by allenhumphreys** [comment]
I like the second option. Is it part of the overview "tab" or will it always be visible?

Also, I wanted to mention that if we're change this area of the UI, you might want to consider issue #233. @insidegui Is there an easy way to make the text scrollable and also automatically resize like it does today?

**Comment by bcmn** [comment]
I’ve looked into #233 before and not made much progress, but I’m not very
au fait with AppKit (& I’m not sure an already implemented app with is
necessarily the best way to learn 🤷🏻‍♂️). There’s some real weirdness
with how the video & the text section below scale in relation to each other.

For what it’s worth, I’d agree whole-heartedly with the second option — I’m
not even slightly convinced people would take the time to click through to
another tab. I think my instinctive expectation from looking at the mock-up
would be that if there was a really long summary, it would be scrollable &
fade “behind” the related videos, with the core details (session no.,
focuses, etc.) at the bottom of the scrollable summary (as in, if it was
lengthy, would they also be out of view, “behind” the related section?)?
They would seem to take up a lot of space when trying to read the more
informative  description otherwise. 🤔

**Comment by allenhumphreys** [comment]
@bcmn I think we're thinking the same about the scrollable summary, the issue I ran into was the scroll view's need of a fixed height. The current text view will grow to a maximum number of lines and shrink accordingly leave no dead space for short summaries. There are ways that we could manually grow and shrink the scroll view to preserve the growing/shrinking behavior. 

> I’m not even slightly convinced people would take the time to click through to
another tab

🤣 So true!

**Comment by insidegui** [comment]
I like the second option better as well, but remember that we have other types of associated resources (sample code, documentation, etc). Those are not contemplated here, we should think about those as well. My suggestion is that we do related sessions like showed in the second example and add another tab called "resources" for sample code, documentation and such.

**Comment by insidegui** [comment]
Another advantage of the second option is we can abstract the content of the sidebar cells to reuse them in that collection, less code to write :)

**Comment by VicenteBorrell** [comment]
Yeah, having the related videos in the Overview tab is a plus. Let's do it!

**Comment by insidegui** [comment]
Ok o/

**Comment by insidegui** [comment]
@bcmn I know you had some work done on the data side for this, how's that going?

**Comment by bcmn** [comment]
Yeah I don't think I'd made significant progress beyond what I uploaded above. I'd thrown together the adaptors to parse the JSON, & SessionAssets now have a collection of resource IDs, but it doesn't finish up associating them to actual Resources yet, which I think would happen in Storage.swift (?).

I was roughly following the pattern of SessionAsset -- When a Session is parsed it gets a collection of SessionResources, each of which are supposed to be resolved to either ResourceRepresentations (for related code, docs or guides) or Sessions (for related videos) -- this resolution should happen in `Storage.swift` but I haven't got around to implementing this for related stuff yet.

This'll all need to be rebased to get up to speed with everything since though.

**Comment by insidegui** [comment]
@bcmn Are you planning on finishing up your implementation on the storage side or should I pick up where you left off?

**Comment by bcmn** [comment]
Looking into it today -- I'll try & rebase everything & see how much I get done, & catch up with you at the end of it. 🙂

**Comment by bcmn** [comment]
Just to keep this issue updated: #367 is now merged, & we’re ready for the UI work on this feature to begin.

I did realise that, whether they’re displayed separately from sessions or not (as Gui proposed above), it might be nice to have icons to represent the three other related resource types in addition to sessions: documentation, guides, & sample code. Do you think you could do something like this, @VicenteBorrell ?

**Comment by insidegui** [comment]
Implemented in #367 and #377
