### ISSUE TITLE
2 frameworks not installed

### ISSUE THREAD

**Issue by hansengj** [insidegui/WWDC#441]
### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS: 11.1.1
- Version of the app: latest downloaded from GitHub on 6/7/2018
- What were you trying to do when the issue happened: run ./bootstrap.sh
- Any particular hardware/software configuration you have that might be affecting the app: Xcode 9.4
- If it is a crash, please provide the crash log: Not a crash.
- If it is a hang (beach ball), please provide a process sample: Not a hang.
- If it is a wrong behavior, list all steps required to reproduce it:
This was the first time I downloaded the Xcode project and built it. I ran into 2 issues running ./boostrap.sh. The RxSwift and realm-cocoa frameworks were not installed because of they are not compatible with Xcode 9.4’s Swift 4.1.2. The app runs fine, but these missing frameworks may cause some features I haven’t used yet to not to be operational.
- Please add screenshots if you think they might help us diagnose the issue: see attachment of terminal output:
![wwdc boostrap output](https://user-images.githubusercontent.com/11789831/41137594-928bae1a-6aa1-11e8-9fa6-c9ec38013af2.png)

**Comment by allenhumphreys** [comment]
@hansengj Thanks for opening an issue. The output from Carthage is actually telling you that those 2 frameworks had to be built from source, not that they weren’t installed. This is because Carthage lets library owners published pre-compiled versions of their libraries to speed setup. When the pre-compiled version isn’t compatible, it falls back to building the library from source. This is what is currently happening for those 2 libraries.
