### ISSUE TITLE
video for WWDC before current year?

### ISSUE THREAD

**Issue by tutumagi** [insidegui/WWDC#481]
Can add a feature that user can watch older WWDC sessions rather than current year like the Official WWDC iOS App? 
Thanks!

**Comment by bcmn** [comment]
Just to be clear, past sessions (Currently 2014+) are under the "Videos" tab. Schedule only includes the most recent schedule.

![screen shot 2018-06-21 at 08 37 28](https://user-images.githubusercontent.com/11646957/41704532-64a0c958-752e-11e8-99ce-c9ba03ab720a.png)

Due to API changes outside of our control, we have no intention to support pre-2014 videos.
