### ISSUE TITLE
Play-control overlay won't go away when cursor moved to a different display

### ISSUE THREAD

**Issue by CoolTomatos** [insidegui/WWDC#538]
### Before opening your issue, please make sure you answer YES to all of the questions below.

- [x] Are you running the latest version of the app?
- [x] Are you running a release, stable version of macOS?
- [x] Have you looked at previous issues to see if you're having an issue that's already being worked on?
- [x] If your issue is about compilation or project setup, have you followed the instructions from the readme?
- [x] Have you read the Code of Conduct, and will you uphold it's values?

### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS:
    - **10.14.4**
- Version of the app: 
    - **6.1**
- What were you trying to do when the issue happened: 
    - **Watching a session in fullscreen mode on my external display**
- Any particular hardware/software configuration you have that might be affecting the app:
    - **External display connected**
- If it is a wrong behavior, list all steps required to reproduce it:
    1. Start playing a video in full screen in external display
    2. Move the cursor back to built-in display, the overlay disappears now as expected.
    3. Click anywhere in the built-in display, the overlay appears unexpected. And it won't go away no matter it is active or idling.

**Comment by allenhumphreys** [comment]
I don't have an external monitor setup to mess with this

**Comment by CoolTomatos** [comment]
@allenhumphreys can you please forward this issue to other developers?

**Comment by allenhumphreys** [comment]
@cooltomatos that’s what I was doing by saying I couldn’t work on it. 👍🏼

**Comment by insidegui** [comment]
I'll try to repro using DuetDisplay and/or AirPlay

**Comment by yigitcanyurtsever** [comment]
Actually, this is caused by calling `showControls(animated: false)` on `NSWindow.didResignMainNotification` notification [here](https://github.com/insidegui/WWDC/blob/master/PlayerUI/Views/PUIPlayerView.swift#L1357).

Removing this line fixes the issue but I didn't want to open a PR directly because I wasn't sure if that line was added for handling something else.

There's also another issue related to this (if you remove the line mentioned above):
If you go full screen and click on another app, the controls and the video dimming goes away, which is great. Then, If you move your cursor back to the video, the controls show up, which makes sense, but leaving the area does not hide the controls. This is because `canHideControls` property returns `false` from this [line](https://github.com/insidegui/WWDC/blob/master/PlayerUI/Views/PUIPlayerView.swift#L1244) because the window/the app is not currently active. 

If removing both these lines would be ok, I can quickly prepare a PR for it.

**Comment by allenhumphreys** [comment]
It sounds like you’ve thoroughly researched the problem and are at a point we’re a PR would allow for an easier logical review! We can also check our your branch and test in a single window environment! So a PR would be very welcome!
