### ISSUE TITLE
If user sets directory with a lot of files as Download folder, app will freeze

### ISSUE THREAD

**Issue by subdan** [insidegui/WWDC#584]
- Version of macOS
10.14.6 (18G103)
- Version of the app
6.1.3
- What were you trying to do when the issue happened
I changed Download folder to ~/Documents
- If it is a hang (beach ball), please provide a process sample
I used Instruments.app and discovered that
`DownloadManager.updateDownloadedFlagsByEnumeratingFilesAtPath`
freezes the app because I changed Downloads folder to ~/Documents where I store all my files (50 Gb).
```
guard let enumerator = FileManager.default.enumerator(atPath: path) else { return }
guard let files = enumerator.allObjects as? [String] else { return }

```
`enumerator.allObjects` freezes the app because I have a lot of files in the Documents directory.

<img width="2160" alt="Screenshot 2019-09-29 at 20 48 02" src="https://user-images.githubusercontent.com/410293/65836685-71c5ca80-e2fa-11e9-9e34-55f1d54e7b1f.png">

As a solution, we can disallow choosing an non-empty directory as Download folder.

Also there is no button to reset Download folder to default value. I think we should add this button. I can open Pull request with this button.

**Comment by allenhumphreys** [comment]
Thanks for investigating this @subdan , unfortunately [we've known about this issue for a while](https://github.com/insidegui/WWDC/issues/544) but just haven't had time to investigate a really good direction on a fix.

One potential short-term solution is to limit the recursion on the file discovery to a set depth. This would likely fix the issue for 95% of use cases as directories with massive numbers of files are usually nested quite deep.

This would be as simple as:
```swift
var files = [String]()
for case let path as String in enumerator {
    // Limit recursion to 2 levels
    if enumerator.level > 2 {
        enumerator.skipDescendants()
    }
    files.append(path)
}
```

A more robust solution would be to only look for files that might actually exist. Since the download filename/path for all possible videos is theoretically known, we could build that list (in the background), then check the existence of expected files.
