### ISSUE TITLE
Subtitle button is missing after download video

### ISSUE THREAD

**Issue by young40** [insidegui/WWDC#657]
- Version of macOS: 10.15.7
- Version of the app: 7.3.3
- What were you trying to do when the issue happened
After download video
![Screen Shot 2021-06-08 at 8 51 29 PM](https://user-images.githubusercontent.com/1680953/121197654-0fc9b080-c8a4-11eb-96e9-bdb09c3add19.png)

**Comment by insidegui** [comment]
This has been a long-standing issue (as seen in #286). Basically the downloaded videos don't include the subtitles (at least not in a way that our player, which is just a wrapper around AVPlayer, understands). So if you rely on subtitles, you'll have to use streaming for now. I'll leave this issue open so that others can reference it.

**Comment by sugarmo** [comment]
> This has been a long-standing issue (as seen in #286). Basically the downloaded videos don't include the subtitles (at least not in a way that our player, which is just a wrapper around AVPlayer, understands). So if you rely on subtitles, you'll have to use streaming for now. I'll leave this issue open so that others can reference it.

Is it possible to convert transcript to subtitles? Putting text in front of the video player should not be that hard (just my opinion).

**Comment by insidegui** [comment]
Tracking this in #267
